galaxy_info:
  author: Victoria Tepliuk
  description: Deploy oauth2-client Docker image

  license: Apache-2.0

  min_ansible_version: 2.4

  platforms:
    - name: EL
      versions:
        - 7

  galaxy_tags:
    - docker
    - xl_auth

dependencies: []
