---

version: '3.4'
services:
  postgres:
    image: postgres:9.4-alpine
    container_name: postgres
    hostname: postgres
    restart: unless-stopped
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - xl_auth
    environment:
      POSTGRES_DB: prod
      POSTGRES_USER: xl_auth
      POSTGRES_PASSWORD: xl_auth

  xl_auth:
    image: mblomdahl/xl_auth:latest
    container_name: xl_auth
    domainname: logging-test.kb.se
    hostname: xl_auth
    restart: always
    environment:
      FLASK_DEBUG: 0
      SQLALCHEMY_DATABASE_URI: 'postgresql://xl_auth:xl_auth@postgres/prod'
    ports:
      - 5000:5000
    networks:
      - xl_auth
    logging:
      driver: gelf
      options:
        gelf-address: udp://localhost:12201
        tag: xl_auth
        mode: non-blocking
    depends_on:
      - postgres

  elk:
    build: ./ansible/roles/logging/files/elk/
    image: elk-ext:611
    container_name: elk
    hostname: elk
    ports:
      - 5601:5601
      - 9200:9200
      - 5044:5044
      - 12201:12201/udp
    volumes:
      - elk:/var/lib/elasticsearch
      - ./ansible/roles/logging/files/elk/02-beats-input.conf:/etc/logstash/conf.d/02-beats-input.conf
      - ./ansible/roles/logging/files/elk/03-gelf-input.conf:/etc/logstash/conf.d/03-gelf-input.conf
      - ./ansible/roles/logging/files/elk/11-nginx.conf:/etc/logstash/conf.d/11-nginx.conf
    networks:
      - logging

  filebeat:
    image: docker.elastic.co/beats/filebeat:6.1.1
    container_name: filebeat
    hostname: filebeat
    command: -e -strict.perms=false
    user: root
    volumes:
      - /var/log:/mnt/log:ro
      - ./ansible/roles/logging/files/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
    networks:
      - logging
    depends_on:
      - elk

volumes:
  postgres:
    driver: local
  elk:
    driver: local

networks:
  xl_auth:
  logging:

...
