---

- name: set timezone to europe/stockholm
  copy: src=/usr/share/zoneinfo/Europe/Stockholm dest=/etc/localtime

- name: add 'root' user to 'wheel'
  user: name=root groups=wheel append=yes

- name: allow 'wheel' group to run password-less sudo without requiretty
  blockinfile:
    dest: /etc/sudoers
    marker: "# {mark} ANSIBLE MANAGED BLOCK common"
    state: absent
    block: |
      %wheel ALL=(ALL) NOPASSWD: ALL
      Defaults!/usr/bin/docker !requiretty
      Defaults:%wheel !requiretty
      Defaults:%wheel visiblepw
    validate: visudo -cf %s

...
