---

- name: install firewalld
  yum: name=firewalld state=present

- name: firewalld running and enabled
  service: name=firewalld state=started enabled=yes

- name: allow incoming ssh traffic (firewalld)
  firewalld: service=ssh permanent=true state=enabled
  notify: restart firewalld

- name: open up port 5601
  firewalld:
    port: 5601/tcp
    source: 10.0.1.32
    state: enabled
    immediate: yes

...
