---

- name: create /opt/logging directory
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /opt
    - /opt/logging
  tags: logging

- name: deploy host-local elk stack
  import_tasks: local-elk-setup.yml
  when: inventory_hostname != 'login.libris.kb.se'
  tags: logging, elk

- name: template /opt/logging/filebeat.yml
  template:
    src: filebeat.yml.j2
    dest: /opt/logging/filebeat.yml
  register: filebeat_config
  tags: logging

- name: (re-)start filebeat
  docker_container:
    name: filebeat
    hostname: filebeat
    image: docker.elastic.co/beats/filebeat:6.1.1
    command: -e -strict.perms=false
    user: root
    state: started
    restart: "{{ filebeat_config.changed }}"
    restart_policy: unless-stopped
    log_driver: syslog
    log_options:
      tag: filebeat
    volume_driver: local
    volumes:
      - /var/log:/mnt/log:ro
      - /opt/logging/filebeat.yml:/usr/share/filebeat/filebeat.yml
    links: "{{ ['elk'] if logging_filebeat_host == 'elk:5044' else [] }}"
  tags: logging

...
