---

- name: template sysctl elk-monitoring.conf
  template: src=elk-monitoring.conf.j2 dest=/usr/lib/sysctl.d/elk-monitoring.conf
  register: logging_sysconfig
  tags: logging

- name: apply sysctl system config
  shell: sysctl --system
  when: logging_sysconfig.changed
  tags: logging

- name: create /opt/logging and /opt/logging/elk directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /opt
    - /opt/logging
    - /opt/logging/elk
  tags: logging

- name: upload logstash configs to /opt/logging/elk/
  copy:
    src: "elk/{{ item }}"
    dest: "/opt/logging/elk/{{ item }}"
  with_items:
    - 02-beats-input.conf
    - 03-gelf-input.conf
    - 11-nginx.conf
    - 30-output.conf
  register: logstash_configs
  tags: logging

- name: upload elk dockerfile to /opt/logging/elk/
  copy:
    src: elk/Dockerfile
    dest: /opt/logging/elk/Dockerfile
  tags: logging

- name: build extended elk image
  docker_image:
    path: /opt/logging/elk/
    name: elk-ext:611
    push: no
    state: present
  register: elk_ext_build
  tags: logging

- name: (re-)start elk
  docker_container:
    name: elk
    hostname: elk
    image: elk-ext:611
    state: started
    restart: "{{ logstash_configs.changed or elk_ext_build.changed }}"
    restart_policy: unless-stopped
    log_driver: syslog
    log_options:
      tag: elk
    volume_driver: local
    volumes:
      - elk:/var/lib/elasticsearch
      - /opt/logging/elk/02-beats-input.conf:/etc/logstash/conf.d/02-beats-input.conf
      - /opt/logging/elk/03-gelf-input.conf:/etc/logstash/conf.d/03-gelf-input.conf
      - /opt/logging/elk/11-nginx.conf:/etc/logstash/conf.d/11-nginx.conf
      - /opt/logging/elk/30-output.conf:/etc/logstash/conf.d/30-output.conf
    ports:
      - 5601:5601
      - 9200:9200
      - 5044:5044
      - 12201:12201/udp
  tags: logging

- name: upload filebeat.yml to /opt/logging/
  copy:
    src: filebeat.yml
    dest: /opt/logging/filebeat.yml
  register: filebeat_config
  tags: logging

- name: (re-)start filebeat
  docker_container:
    name: filebeat
    hostname: filebeat
    image: docker.elastic.co/beats/filebeat:6.1.1
    command: -e -strict.perms=false
    user: root
    state: started
    restart: "{{ filebeat_config.changed }}"
    restart_policy: unless-stopped
    log_driver: syslog
    log_options:
      tag: filebeat
    volume_driver: local
    volumes:
      - /var/log:/mnt/log:ro
      - /opt/logging/filebeat.yml:/usr/share/filebeat/filebeat.yml
    links:
      - elk
  tags: logging

...
