########################### Filebeat Configuration ###########################

#==========================  Modules configuration ===========================
filebeat.modules:

#-------------------------------- Nginx Module -------------------------------
- module: nginx
  access:
    enabled: true
    var.paths: ["/mnt/log/nginx/access.log*"]
  error:
    enabled: true
    var.paths: ["/mnt/log/nginx/error.log*"]


#================================ Outputs ====================================

#-------------------------- Elasticsearch output -----------------------------
output.elasticsearch:
  hosts: ["elk:9200"]


#================================ Kibana =====================================
setup.kibana:
  host: "http://elk:5601"


#=============================== Logging =====================================
logging.json: true

...
