---

- name: docker-ce repo
  yum_repository:
    name: docker-ce-stable
    description: Docker CE Stable - $basearch
    baseurl: https://download.docker.com/linux/centos/7/$basearch/stable
    gpgkey: https://download.docker.com/linux/centos/gpg
  tags: docker

- name: install docker-ce-17.09.1.ce
  yum: name=docker-ce-17.09.1.ce state=present allow_downgrade=yes
  register: yum_install_docker
  tags: docker

- name: lock docker-ce version
  shell: yum versionlock docker-ce
  when: yum_install_docker.changed
  tags: docker

- name: install docker-compose-1.16.1
  pip: name=docker-compose version=1.16.1 state=present
  tags: docker

- name: template docker daemon.json
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
  notify: restart docker
  tags: docker

- name: docker running and enabled
  service: name=docker state=started enabled=yes
  tags: docker

...
