---

- name: run oauth2-client
  docker_container:
    name:  oauth2-client
    image: tepliuk/oauth2-client
    pull: yes
    state: started
    ports:
      - 80:5001
    env:
        FLASK_APP: app.py
        APP_SECRET_KEY: "{{ APP_SECRET_KEY }}"
        OAUTH2_BASE_URL: "{{ OAUTH2_BASE_URL }}"
        OAUTH2_CLIENT_SECRET: "{{ OAUTH2_CLIENT_SECRET }}"
        OAUTH2_CLIENT_ID: "{{ OAUTH2_CLIENT_ID }}"
        OAUTH2_CLIENT_REDIRECT_URI: "{{ OAUTH2_CLIENT_REDIRECT_URI }}"

...
